name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # allows manual trigger from Actions tab
  push:
    branches:
      - main

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVGs
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: harshxyxo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#7C3AED,#a5f3fc,#38bdf8,#818cf8,#7C3AED

      - name: Push snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
